#!/bin/bash


#!/bin/sh

# ai_hw_probe.sh - Inventory GPU/NPU/AI accelerator presence on NXP-based embedded systems

# Target: Vertiv MRIC-RP (i.MX8M Mini) / IMD5

# Author: Ed Thompson (generated by M365 Copilot)

# Shell: POSIX sh (BusyBox compatible)



set -u



# ------------ helpers ------------

banner() { echo "=== $* ==="; }

have() { command -v "$1" >/dev/null 2>&1; }

grep_i() { grep -E -i "$1"; }

log()

{

  # print section label + value (if provided)

  if [ $# -eq 1 ]; then

    printf "%s\n" "$1"

  else

    printf "%-24s : %s\n" "$1" "$2"

  fi

}



print_file_if_exists()

{

  f="$1"

  if [ -r "$f" ]; then

    echo "$f:"

    sed -n '1,120p' "$f"

  fi

}



try_run()

{

  cmd="$*"

  if have $(echo "$cmd" | awk '{print $1}'); then

    echo "\$ $cmd"

    # limit long outputs

    sh -c "$cmd" 2>&1 | sed -n '1,120p'

  else

    echo "missing: $(echo "$cmd" | awk '{print $1}')"

  fi

}



# ------------ 1. CPU / SoC identity ------------

banner "SoC / CPU"

if [ -r /proc/cpuinfo ]; then

  # summarize implementer, part, model name

  awk '

    /Hardware|Model|processor|CPU architecture|CPU part|CPU implementer|model name/ {

      gsub(/\r/,""); print

    }' /proc/cpuinfo

else

  echo "No /proc/cpuinfo"

fi



# Device tree compatible strings often reveal SoC SKU

if [ -r /proc/device-tree/compatible ]; then

  echo "/proc/device-tree/compatible:"

  tr -d '\000' < /proc/device-tree/compatible | tr ',' '\n'

fi

[ -r /sys/firmware/devicetree/base/model ] && {

  echo "/sys/firmware/devicetree/base/model:"

  tr -d '\000' < /sys/firmware/devicetree/base/model

}



# ------------ 2. Kernel dmesg probe ------------

banner "Kernel dmesg (GPU/NPU/DSP keywords)"

DMESG="$(have dmesg && dmesg 2>/dev/null || true)"

echo "$DMESG" | grep -E -i 'vivante|galcore|etnaviv|imx-gpu|gc[0-9]+|mxc_g2d|g2d|pxp|imx-pxp|drm|etnaviv|vsi|npu|neural|ethos|tpu|cuda|opencl|vc4|lima|panfrost' | sed -n '1,200p' || echo "No matching dmesg lines."



# ------------ 3. Device nodes ------------

banner "Device nodes (indicators)"

for d in /dev/dri /dev/galcore /dev/mxc_g2d /dev/pxp /dev/vsi*; do

  [ -e "$d" ] && ls -l "$d"

done

# list DRI minors if present

[ -d /dev/dri ] && ls -l /dev/dri



# ------------ 4. DRM / GPU sysfs ------------

banner "DRM sysfs"

if [ -d /sys/class/drm ]; then

  for n in /sys/class/drm/card*; do

    [ -d "$n" ] || continue

    log "DRM node" "$(basename "$n")"

    [ -r "$n/device/modalias" ] && log "modalias" "$(cat "$n/device/modalias")"

    [ -r "$n/device/vendor" ] && log "vendor" "$(cat "$n/device/vendor")"

    [ -r "$n/device/device" ] && log "device" "$(cat "$n/device/device")"

  done

else

  echo "No /sys/class/drm"

fi



# ------------ 5. Modules & kernel drivers ------------

banner "Loaded modules (GPU/NPU/DSP)"

if have lsmod; then

  lsmod | grep -E -i 'etnaviv|galcore|imx_gpu|mxc_g2d|pxp|drm|gpu|opencl|vsi|npu|ethos|tpu' || echo "No relevant modules loaded."

else

  echo "lsmod not available."

fi



banner "Available kernel objects (scan)"

MODDIR="/lib/modules/$(uname -r)"

if [ -d "$MODDIR" ]; then

  find "$MODDIR" -type f -name '*.ko' -printf '%P\n' | \

    grep -E -i 'etnaviv|galcore|imx.*gpu|mxc_g2d|pxp|drm|vsi|npu|ethos|tpu' || echo "No relevant .ko files found."

else

  echo "No module directory: $MODDIR"

fi



# ------------ 6. Libraries / runtimes ------------

banner "Libraries indicating GPU/NPU runtimes"

LIBPATHS="/usr/lib /usr/local/lib /lib"

for p in $LIBPATHS; do

  [ -d "$p" ] || continue

  echo "Scanning $p"

  ls "$p" | grep -E -i 'libEGL|libGLES|libGL|libOpenCL|libvsi|libethosu|libtpu|libnvinfer|libcuda' || echo "None in $p"

done



# ------------ 7. GL/EGL renderer strings ------------

banner "GL/EGL renderer strings"

if have glxinfo; then

  glxinfo | grep_i 'OpenGL vendor|OpenGL renderer|OpenGL version'

elif have es2_info; then

  es2_info | grep_i 'Vendor|Renderer|Version'

elif have eglinfo; then

  eglinfo | sed -n '1,200p'

else

  echo "No glxinfo/es2_info/eglinfo installed."

fi



# ------------ 8. OpenCL platforms ------------

banner "OpenCL platforms"

if have clinfo; then

  clinfo | sed -n '1,120p'

else

  echo "clinfo not installed."

fi



# ------------ 9. USB/PCI hints (Coral/NVIDIA) ------------

banner "Hardware buses"

if have lsusb; then

  lsusb | grep -E -i 'Google|Coral|GlobalUnichip|NVIDIA|AMD|Intel.*Graphics' || echo "No accelerator-class USB devices."

else

  echo "lsusb not available."

fi



if have lspci; then

  lspci -nn | grep -E -i 'VGA|3D|Display|NVIDIA|AMD|GPU' || echo "No PCIe GPU devices."

else

  echo "lspci not available."

fi



# ------------ 10. Verdict synthesis ------------

banner "Verdict (heuristic)"



has_gpu="no"

has_npu="no"



# GPU flags

[ -e /dev/dri/card0 ] && has_gpu="yes"

[ -e /dev/galcore ] && has_gpu="yes"

[ -e /dev/mxc_g2d ] && has_gpu="yes"

echo "$DMESG" | grep -qiE 'vivante|galcore|etnaviv|drm' && has_gpu="yes"



# NPU/DSP flags

echo "$DMESG" | grep -qiE 'npu|ethos|vsi|tpu|neural' && has_npu="yes"

for p in $LIBPATHS; do

  ls "$p" 2>/dev/null | grep -qiE 'libvsi|libethosu|libtpu' && has_npu="yes"

done



log "GPU detected" "$has_gpu"

log "NPU/DSP detected" "$has_npu"



# ------------ 11. Extra: platform expectations ------------

banner "Platform expectations (i.MX8M Mini/Micro)"

echo "On MRIC-RP (i.MX8M Mini), expectation is: NO 3D GPU/NPU; possible 2D engines (PXP/G2D)."

echo "If you see /dev/mxc_g2d or dmesg lines for 'pxp'/'g2d', that is a 2D blitter—not an AI accelerator."



banner "Done"

exit 0


